// The question bank. `correct` is the index of the right option. It is encrypted before it is stored.
export const PACKS = [
  {
    slug: 'system-design',
    title: 'System Design Showdown',
    category: 'Tech',
    emoji: '🧠',
    description: 'Load balancers, consensus, caches and queues. The whole series in one quiz.',
    questions: [
      ['Which HTTP status code means "Too Many Requests"?', ['400', '403', '429', '503'], 2, 'Rate limiters send it, often with a Retry-After header.'],
      ['In the CAP theorem, what does the P stand for?', ['Performance', 'Partition tolerance', 'Persistence', 'Parallelism'], 1, 'During a network partition you must pick consistency or availability.'],
      ['Which consensus algorithm does etcd use?', ['Paxos', 'Raft', 'Gossip', 'Two-phase commit'], 1, 'Raft elects one leader; a write needs a majority of nodes.'],
      ['A 5-node Raft cluster keeps accepting writes with how many nodes down?', ['1', '2', '3', '4'], 1, '3 of 5 is still a majority.'],
      ['What does a CDN mainly reduce for users far from your servers?', ['Storage cost', 'Latency', 'Write conflicts', 'CPU usage'], 1, 'Copies sit at edges near the users.'],
      ['Which Redis data structure fits a leaderboard best?', ['List', 'Set', 'Sorted set', 'Hash'], 2, 'ZINCRBY to add points, ZREVRANK to find your place.'],
      ['An operation is "idempotent" when…', ['it is encrypted', 'doing it twice has the same effect as once', 'it is replicated', 'it never fails'], 1, 'That is what makes retries safe.'],
      ['Which pattern stops a service from calling a broken dependency again and again?', ['Circuit breaker', 'Sharding', 'Fan-out', 'Write-ahead log'], 0, 'After a few failures it "opens" and fails fast for a while.'],
      ['What does a fencing token protect against?', ['SQL injection', 'An old leader writing after a new one took over', 'Slow disks', 'Cache misses'], 1, 'Storage rejects writes carrying an older token.'],
      ['Which lets browser and server both send messages at any time over one connection?', ['Server-Sent Events', 'Long polling', 'WebSocket', 'HTTP/1.0'], 2, 'It starts as HTTP, then upgrades.'],
      ['In the transactional outbox pattern, where is the message written first?', ['A Kafka topic', 'The same DB transaction as the data', 'A Redis cache', 'An email'], 1, 'A relay publishes it afterwards, so it can never be lost.'],
      ['Which load-balancing strategy picks the server with the fewest open connections?', ['Round robin', 'Least connections', 'IP hash', 'Random'], 1, 'Good when requests take very different times.'],
      ['What is "p99 latency"?', ['The average response time', 'The time 99% of requests beat', 'The slowest request ever', '99 milliseconds'], 1, 'Tail latency is what unlucky users feel.'],
      ['Which PostgreSQL index type is used for full-text search?', ['B-tree', 'Hash', 'GIN', 'BRIN'], 2, 'A Generalized Inverted Index maps words to rows.'],
    ],
  },
  {
    slug: 'india',
    title: 'India Quiz Night',
    category: 'India',
    emoji: '🇮🇳',
    description: 'History, places and people from across India.',
    questions: [
      ['Which is the national aquatic animal of India?', ['Ganges river dolphin', 'Mugger crocodile', 'Olive ridley turtle', 'Whale shark'], 0, 'It was declared the national aquatic animal in 2009.'],
      ['In which year did Chandrayaan-3 land near the Moon\'s south pole?', ['2019', '2021', '2023', '2024'], 2, 'The Vikram lander touched down on 23 August 2023.'],
      ['Which city is known as the "Pink City"?', ['Jodhpur', 'Jaipur', 'Udaipur', 'Bikaner'], 1, 'Painted pink to welcome the Prince of Wales in 1876.'],
      ['The Brahmaputra enters India in which state?', ['Assam', 'Arunachal Pradesh', 'Sikkim', 'Meghalaya'], 1, 'It is called the Siang there.'],
      ['Which Indian state has the longest coastline?', ['Tamil Nadu', 'Maharashtra', 'Gujarat', 'Andhra Pradesh'], 2, 'Gujarat has over 1,600 km of coast.'],
      ['Who wrote "Jana Gana Mana"?', ['Bankim Chandra Chatterjee', 'Rabindranath Tagore', 'Sarojini Naidu', 'Subramania Bharati'], 1, 'Tagore also wrote Bangladesh\'s anthem.'],
      ['Which is the oldest IIT?', ['IIT Bombay', 'IIT Madras', 'IIT Kharagpur', 'IIT Delhi'], 2, 'IIT Kharagpur was founded in 1951, in the old Hijli detention camp.'],
      ['The Konark Sun Temple is in which state?', ['Odisha', 'West Bengal', 'Andhra Pradesh', 'Bihar'], 0, 'It is built as a giant stone chariot with 24 wheels.'],
      ['In which year was the ₹ symbol adopted?', ['2005', '2010', '2014', '2016'], 1, 'Designed by D. Udaya Kumar.'],
      ['Which mathematician is linked with the "taxicab number" 1729?', ['Aryabhata', 'Srinivasa Ramanujan', 'Bhaskara II', 'C. R. Rao'], 1, '1729 is the smallest number that is a sum of two cubes in two ways.'],
      ['Since 2019, how many states has India had?', ['28', '29', '30', '31'], 0, 'Jammu and Kashmir became a union territory in 2019.'],
      ['Kathakali is a classical dance from which state?', ['Tamil Nadu', 'Kerala', 'Karnataka', 'Manipur'], 1, 'Known for its painted faces and huge costumes.'],
    ],
  },
  {
    slug: 'science-space',
    title: 'Science Sprint',
    category: 'Science',
    emoji: '🔬',
    description: 'Atoms, cells and planets. Fast questions for curious minds.',
    questions: [
      ['What is the chemical symbol for gold?', ['Go', 'Gd', 'Au', 'Ag'], 2, 'From the Latin "aurum".'],
      ['Which planet has the shortest day?', ['Earth', 'Mars', 'Jupiter', 'Mercury'], 2, 'Jupiter spins once in about 10 hours.'],
      ['Roughly how long does sunlight take to reach Earth?', ['8 seconds', '8 minutes', '8 hours', '1 day'], 1, 'About 8 minutes 20 seconds.'],
      ['Which part of a cell makes most of its ATP?', ['Nucleus', 'Ribosome', 'Mitochondrion', 'Golgi body'], 2, 'The "powerhouse of the cell".'],
      ['Which gas makes up most of Earth\'s atmosphere?', ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'], 1, 'About 78% nitrogen.'],
      ['What is the speed of light in a vacuum, roughly?', ['300 km/s', '3,000 km/s', '300,000 km/s', '3,000,000 km/s'], 2, 'About 299,792 km per second.'],
      ['Which particle has no electric charge?', ['Proton', 'Electron', 'Neutron', 'Positron'], 2, 'Discovered by James Chadwick in 1932.'],
      ['What is the hardest natural substance?', ['Quartz', 'Diamond', 'Titanium', 'Graphite'], 1, 'Both diamond and graphite are pure carbon.'],
      ['Which planet has the Great Red Spot?', ['Mars', 'Saturn', 'Jupiter', 'Neptune'], 2, 'A storm bigger than Earth.'],
      ['What is H₂O₂?', ['Water', 'Hydrogen peroxide', 'Ozone', 'Heavy water'], 1, 'Used as a mild antiseptic.'],
      ['At sea level, water boils at…', ['90 °C', '100 °C', '110 °C', '120 °C'], 1, 'Higher up, the boiling point drops.'],
      ['Who wrote down the three laws of motion?', ['Galileo', 'Isaac Newton', 'Johannes Kepler', 'Albert Einstein'], 1, 'Published in the Principia in 1687.'],
    ],
  },
  {
    slug: 'geography',
    title: 'Around the World',
    category: 'Geography',
    emoji: '🌍',
    description: 'Capitals, oceans, mountains and straits.',
    questions: [
      ['Which is the largest ocean?', ['Atlantic', 'Indian', 'Arctic', 'Pacific'], 3, 'It covers about a third of the Earth.'],
      ['What is the capital of Australia?', ['Sydney', 'Melbourne', 'Canberra', 'Perth'], 2, 'Built as a compromise between Sydney and Melbourne.'],
      ['Which country became the most populous in 2023, per UN estimates?', ['China', 'India', 'USA', 'Indonesia'], 1, 'India passed China in 2023.'],
      ['Mount Kilimanjaro is in which country?', ['Kenya', 'Tanzania', 'Uganda', 'Ethiopia'], 1, 'Africa\'s highest mountain.'],
      ['Which is the largest hot desert?', ['Gobi', 'Kalahari', 'Sahara', 'Thar'], 2, 'About the size of the USA.'],
      ['The Danube flows into which sea?', ['Baltic Sea', 'Black Sea', 'Mediterranean Sea', 'North Sea'], 1, 'It passes through 10 countries.'],
      ['Which country has the most time zones, counting overseas territories?', ['Russia', 'USA', 'France', 'China'], 2, 'Thanks to territories across the oceans.'],
      ['What is the capital of Canada?', ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], 1, 'Chosen by Queen Victoria in 1857.'],
      ['Which strait separates Asia from North America?', ['Strait of Gibraltar', 'Bering Strait', 'Strait of Hormuz', 'Strait of Malacca'], 1, 'Only about 82 km wide at its narrowest.'],
      ['Lake Baikal, the deepest lake, is in which country?', ['Canada', 'Russia', 'Mongolia', 'Kazakhstan'], 1, 'It holds about a fifth of the world\'s surface fresh water.'],
      ['Istanbul is in which country?', ['Greece', 'Türkiye', 'Georgia', 'Bulgaria'], 1, 'The city sits on both Europe and Asia.'],
      ['What is the smallest country by area?', ['Monaco', 'Vatican City', 'San Marino', 'Malta'], 1, 'About 0.44 square kilometres.'],
    ],
  },
  {
    slug: 'cs-basics',
    title: 'CS Fundamentals',
    category: 'Tech',
    emoji: '💻',
    description: 'Data structures, algorithms and the web. Placement-season warm-up.',
    questions: [
      ['Time complexity of binary search on a sorted array?', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 1, 'Each step halves what is left.'],
      ['Which data structure is First-In-First-Out?', ['Stack', 'Queue', 'Tree', 'Heap'], 1, 'Like a line at a ticket counter.'],
      ['How many bits are in a byte?', ['4', '8', '16', '32'], 1, 'Half a byte is a nibble.'],
      ['Which sort is O(n log n) even in the worst case?', ['Quick sort', 'Bubble sort', 'Merge sort', 'Insertion sort'], 2, 'Quick sort can hit O(n²) with bad pivots.'],
      ['What does SQL stand for?', ['Structured Query Language', 'Simple Question Language', 'Sequential Query Logic', 'Server Query Layer'], 0, 'Born at IBM in the 1970s.'],
      ['Which port does HTTPS use by default?', ['80', '22', '443', '8080'], 2, 'Port 80 is plain HTTP.'],
      ['What does DNS translate?', ['IP addresses to MAC addresses', 'Domain names to IP addresses', 'HTML to CSS', 'Ports to processes'], 1, 'The internet\'s phone book.'],
      ['Which of these is NOT a primitive type in JavaScript?', ['string', 'number', 'object', 'boolean'], 2, 'Objects are reference types.'],
      ['Which Git command records a new commit?', ['git push', 'git commit', 'git add', 'git fetch'], 1, 'git add only stages changes.'],
      ['Which traversal of a binary search tree gives sorted order?', ['Pre-order', 'In-order', 'Post-order', 'Level-order'], 1, 'Left, node, right.'],
      ['What does HTTP 404 mean?', ['Server error', 'Not found', 'Forbidden', 'Moved permanently'], 1, '5xx codes are server errors.'],
      ['Which algorithm finds shortest paths from one source with non-negative weights?', ['Depth-first search', 'Dijkstra\'s algorithm', 'Kruskal\'s algorithm', 'Prim\'s algorithm'], 1, 'Kruskal and Prim build minimum spanning trees.'],
    ],
  },
  {
    slug: 'sports',
    title: 'Game, Set, Quiz',
    category: 'Sports',
    emoji: '🎾',
    description: 'Cricket, tennis, the Olympics and more.',
    questions: [
      ['How many players does one cricket team have on the field?', ['9', '10', '11', '12'], 2, 'Plus substitutes who may field but not bat.'],
      ['Which Grand Slam is played on clay?', ['Wimbledon', 'US Open', 'French Open', 'Australian Open'], 2, 'Roland-Garros, in Paris.'],
      ['In tennis, what is a score of zero called?', ['Nil', 'Love', 'Duck', 'Blank'], 1, 'A "duck" is zero in cricket.'],
      ['Who won the first Cricket World Cup in 1975?', ['England', 'Australia', 'West Indies', 'India'], 2, 'They won again in 1979.'],
      ['How long is a marathon?', ['21.1 km', '40 km', '42.195 km', '50 km'], 2, 'The distance comes from the 1908 London Olympics.'],
      ['How many rings are on the Olympic flag?', ['4', '5', '6', '7'], 1, 'One for each inhabited continent group.'],
      ['Who won India\'s javelin gold at the Tokyo Olympics?', ['Neeraj Chopra', 'Abhinav Bindra', 'P. V. Sindhu', 'Bajrang Punia'], 0, 'His winning throw was 87.58 m.'],
      ['A standard tennis tie-break is played to how many points?', ['5', '7', '10', '15'], 1, 'You must also win by two.'],
      ['How many legal balls are in an over in cricket?', ['4', '5', '6', '8'], 2, 'Eight-ball overs were once used in Australia.'],
      ['Which sport uses a shuttlecock?', ['Squash', 'Badminton', 'Table tennis', 'Volleyball'], 1, 'Smashes can pass 400 km/h.'],
    ],
  },
  {
    slug: 'general',
    title: 'Friday Night Trivia',
    category: 'General',
    emoji: '🎲',
    description: 'A bit of everything. The classic pub quiz.',
    questions: [
      ['How many continents are there in the most common model?', ['5', '6', '7', '8'], 2, 'Some models merge the Americas or Europe and Asia.'],
      ['What is the largest mammal?', ['African elephant', 'Blue whale', 'Giraffe', 'Sperm whale'], 1, 'It can weigh over 150 tonnes.'],
      ['How many sides does a hexagon have?', ['5', '6', '7', '8'], 1, 'Honeycomb cells are hexagons.'],
      ['Which vitamin does skin make in sunlight?', ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], 3, 'UVB light starts the process.'],
      ['What is the freezing point of water in Fahrenheit?', ['0 °F', '32 °F', '100 °F', '212 °F'], 1, '212 °F is the boiling point.'],
      ['Which instrument usually has 88 keys?', ['Guitar', 'Piano', 'Violin', 'Flute'], 1, '52 white keys and 36 black keys.'],
      ['How many hours are in a week?', ['144', '168', '172', '186'], 1, '7 × 24.'],
      ['What is the largest organ of the human body?', ['Liver', 'Brain', 'Skin', 'Lungs'], 2, 'About 16% of body weight.'],
      ['Which of these is a prime number?', ['21', '27', '29', '33'], 2, '29 has no divisors except 1 and itself.'],
      ['Mixing blue and yellow paint gives…', ['Green', 'Purple', 'Orange', 'Brown'], 0, 'Blue and red make purple.'],
      ['How many minutes are in a day?', ['1,140', '1,440', '1,400', '2,440'], 1, '24 × 60.'],
      ['Which language has the most native speakers?', ['English', 'Hindi', 'Mandarin Chinese', 'Spanish'], 2, 'English has the most speakers in total.'],
    ],
  },
];

export const USERS = [
  { email: 'admin@buzzarena.dev', name: 'Anita', role: 'admin', password: 'arena-admin-2026' },
  { email: 'meera@buzzarena.dev', name: 'Meera', role: 'host', password: 'host-meera-2026' },
  { email: 'rohan@buzzarena.dev', name: 'Rohan', role: 'host', password: 'host-rohan-2026' },
  { email: 'asha@buzzarena.dev', name: 'Asha', role: 'player', password: 'play-asha-2026' },
  { email: 'kabir@buzzarena.dev', name: 'Kabir', role: 'player', password: 'play-kabir-2026' },
  { email: 'priya@buzzarena.dev', name: 'Priya', role: 'player', password: 'play-priya-2026' },
  { email: 'vikram@buzzarena.dev', name: 'Vikram', role: 'player', password: 'play-vikram-2026' },
  { email: 'zoya@buzzarena.dev', name: 'Zoya', role: 'player', password: 'play-zoya-2026' },
];
